name: Unzip and Deploy

on:
  push:
    paths:
      - 'wheelsdrive.zip'

jobs:
  unzip:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Unzip project
        run: |
          unzip -o wheelsdrive.zip
          cp -r wheelsdrive/. .
          rm -rf wheelsdrive wheelsdrive.zip

      - name: Commit & Push to Repository
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add -A
          git diff --cached --quiet && echo "Nothing to commit" || git commit -m "Extract WheelsDrive project"
          git push origin main --force
