name: Extract ZIP

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Remove old extracted folder
        run: rm -rf extracted

      - name: Extract ZIP
        run: unzip wheelsdrive_upgraded.zip -d extracted

      - name: Show files
        run: ls -R extracted

      - name: Commit extracted files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add extracted
          git commit -m "Auto extract zip" || echo "No changes"

          git push
